# Generated by Django 4.2.2 on 2023-12-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0003_alter_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, default='../post_default.png', null=True, upload_to='static'),
        ),
    ]
